service: med-manager
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  profile: mitch

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    MedicationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Medications
        AttributeDefinitions:
          - AttributeName: patientId
            AttributeType: S
          - AttributeName: medicationId
            AttributeType: S
        KeySchema:
          - AttributeName: patientId
            KeyType: HASH
          - AttributeName: medicationId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST